# Generated by Django 5.0.1 on 2024-01-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_aboutpage_quizzpage_sharkspage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharkpage",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
