# Generated by Django 5.0.1 on 2024-02-20 20:45

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_sharkpage_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="title")),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
